from enum import StrEnum


class Role(StrEnum):
    PLATFORM_OWNER = "platform_owner"
    ACADEMY_DIRECTOR = "academy_director"
    BRANCH_MANAGER = "branch_manager"
    BRANCH_ADMIN = "branch_admin"
    TEACHER = "teacher"
    PARENT = "parent"
    STUDENT = "student"


class ScopeType(StrEnum):
    PLATFORM = "platform"
    ACADEMY = "academy"
    BRANCH = "branch"
    ASSIGNED_CLASS = "assigned_class"
    LINKED_STUDENT = "linked_student"
    SELF = "self"


class Permission(StrEnum):
    PLATFORM_MANAGE = "platform.manage"
    SYSTEM_HEALTH_VIEW = "system_health.view"
    ACADEMY_VIEW = "academy.view"
    ACADEMY_MANAGE = "academy.manage"
    BRANCH_VIEW = "branch.view"
    BRANCH_CREATE = "branch.create"
    BRANCH_EDIT = "branch.edit"
    BRANCH_ARCHIVE = "branch.archive"
    USER_VIEW = "user.view"
    USER_CREATE = "user.create"
    ROLE_ASSIGN = "role.assign"
    ROLE_REVOKE = "role.revoke"
    STUDENT_VIEW = "student.view"
    STUDENT_CREATE = "student.create"
    STUDENT_EDIT = "student.edit"
    STUDENT_ARCHIVE = "student.archive"
    TEACHER_VIEW = "teacher.view"
    TEACHER_CREATE = "teacher.create"
    TEACHER_EDIT = "teacher.edit"
    CLASS_VIEW = "class.view"
    CLASS_MANAGE = "class.manage"
    SCHEDULE_VIEW = "schedule.view"
    SCHEDULE_CREATE = "schedule.create"
    SCHEDULE_EDIT = "schedule.edit"
    SCHEDULE_REQUEST_RESCHEDULE = "schedule.request_reschedule"
    SCHEDULE_APPROVE_RESCHEDULE = "schedule.approve_reschedule"
    SCHEDULE_CANCEL = "schedule.cancel"
    ATTENDANCE_VIEW = "attendance.view"
    ATTENDANCE_CREATE = "attendance.create"
    ATTENDANCE_EDIT = "attendance.edit"
    ATTENDANCE_FINALIZE = "attendance.finalize"
    ATTENDANCE_REQUEST_EDIT = "attendance.request_edit"
    ATTENDANCE_APPROVE_EDIT = "attendance.approve_edit"
    LESSON_SUMMARY_VIEW = "lesson_summary.view"
    LESSON_SUMMARY_CREATE = "lesson_summary.create"
    LESSON_SUMMARY_EDIT = "lesson_summary.edit"
    LESSON_SUMMARY_PUBLISH = "lesson_summary.publish"
    LESSON_SUMMARY_REQUEST_EDIT = "lesson_summary.request_edit"
    LESSON_SUMMARY_APPROVE_EDIT = "lesson_summary.approve_edit"
    MATERIAL_VIEW = "material.view"
    MATERIAL_UPLOAD = "material.upload"
    MATERIAL_APPROVE = "material.approve"
    MATERIAL_ARCHIVE = "material.archive"
    MATERIAL_DISTRIBUTE = "material.distribute"
    INVOICE_VIEW = "invoice.view"
    INVOICE_CREATE = "invoice.create"
    INVOICE_EDIT = "invoice.edit"
    PAYMENT_CONFIRM = "payment.confirm"
    PAYMENT_PROOF_UPLOAD = "payment_proof.upload"
    SUBSCRIPTION_VIEW = "subscription.view"
    SUBSCRIPTION_MANAGE = "subscription.manage"
    ADDON_BUY = "addon.buy"
    COMMUNICATION_VIEW = "communication.view"
    COMMUNICATION_SEND = "communication.send"
    COMMUNICATION_MODERATE = "communication.moderate"
    REPORT_VIEW = "report.view"
    AUDIT_LOG_VIEW = "audit_log.view"
